[package]
name = "adversary"
version = "0.1.0"
edition = "2018"
publish = false
authors = ["Libra <oncall+libra@xmail.facebook.com>"]

[dependencies]
tokio = { version = "1.5.0", features = ["sync", "rt", "macros", "time"] }
log = "0.4.14"

